
                    </div>

                    <div class="col-sm"></div>
                    <div class="col-sm"></div>

                </div>

                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm h-25">
                            <nav class="navbar navbar-expand-lg fixed-bottom navbar-light bg-light" id="mainnav">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
                                    <div class="navbar-nav">
                                        <a class="nav-item nav-link" href="#">Sortiment</a>
                                        <a class="nav-item nav-link" href="#">Om os</a>
                                        <a class="nav-item nav-link" href="#">Kontakt</a>
                                    </div>
                                </div>
                            </nav>
                        </div>
                    </div>
            </div>

        </body>
</html>